name: Luu D Van, 4298 - my Uni Code
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  tags:
    output: true
    permalink: tags/:path/
sass:
  style: compact
